apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: local-alysis-tmpl
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: prom-tmpl
      initialDelay: 30s
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: opsmx-provider-account
                containers:
                - name: tmpl-gitops
                  image: 'quay.io/opsmxpublic/argo-isd-metric-provider-job:v1.3.0'
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: gitopstemplates
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: local-provider-config
                - name: gitopstemplates
                  projected:
                    sources:
                    - configMap:
                        name: prometheus-verifier
                    - configMap:
                        name: elastic-verifier
                - name: secret-config-volume
                  secret:
                    secretName: local-opsmx-profile
                    optional: false
