apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx-ldap
  name: nginx-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-ldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: nginx-ldap
    spec:
      containers:
      - image: bitnami/nginx-ldap-auth-daemon
        env:
         -  name: NGINXLDAP_LDAP_URI
            value: "ldap://openldap:389"                   # we can use custom ldap also
         -  name: NGINXLDAP_LDAP_BASE_DN
            value: "dc=example,dc=org"
         -  name: NGINXLDAP_LDAP_BIND_DN
            value: "cn=admin,dc=example,dc=org"
         -  name: NGINXLDAP_LDAP_BIND_PASSWORD
            valueFrom: 
               secretKeyRef:
                  name: openldap
                  key: LDAP_ADMIN_PASSWORD
         -  name: NGINXLDAP_LDAP_FILTER
            value: "(cn=%(username)s)"
        imagePullPolicy: Always
        name: nginx-ldap
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
